### ISSUE TITLE
Replace examples that don't support "Negative Values"

### ISSUE THREAD

**Issue by thierryk** [nueverest/blowdrycss#4]
In the examples related to [negative values](http://blowdrycss.readthedocs.io/en/latest/syntax.html#negative-values), 2 relate to dimensions (`width`/`height`) for which negative values do not mean much.

Same issue with the padding example [here](http://blowdrycss.readthedocs.io/en/latest/syntax.html#use-underscores-to-indicate-decimal-point).

**Comment by nueverest** [comment]
Fixed
